CREATE TABLE IF NOT EXISTS sma_crossover_executions (
    id TEXT PRIMARY KEY,
    strategy_id TEXT NOT NULL,
    exchange_connection_id TEXT NOT NULL,
    execution_type TEXT NOT NULL,
    trigger_reason TEXT NOT NULL,
    amount_usd REAL NOT NULL,
    amount_asset REAL,
    price_at_execution REAL NOT NULL,
    fast_sma_value REAL NOT NULL,
    slow_sma_value REAL NOT NULL,
    sma_spread REAL NOT NULL,
    signal_strength TEXT NOT NULL,
    crossover_type TEXT,
    position_before INTEGER NOT NULL,
    position_after INTEGER NOT NULL,
    realized_pnl REAL,
    order_id TEXT,
    order_status TEXT NOT NULL,
    execution_timestamp TEXT NOT NULL,
    error_message TEXT,
    created_at TEXT NOT NULL,
    FOREIGN KEY (strategy_id) REFERENCES sma_crossover_strategies (id) ON DELETE CASCADE,
    FOREIGN KEY (exchange_connection_id) REFERENCES exchange_connections (id) ON DELETE CASCADE
);
