CREATE TABLE IF NOT EXISTS dca_strategies (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL,
    name TEXT NOT NULL,
    asset_symbol TEXT NOT NULL,
    total_allocation TEXT NOT NULL,
    base_tranche_size TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'active',
    strategy_type TEXT NOT NULL DEFAULT 'adaptive_zone',
    sentiment_multiplier BOOLEAN NOT NULL DEFAULT 0,
    volatility_adjustment BOOLEAN NOT NULL DEFAULT 0,
    fear_greed_threshold_buy INTEGER NOT NULL DEFAULT 25,
    fear_greed_threshold_sell INTEGER NOT NULL DEFAULT 75,
    max_tranche_percentage TEXT NOT NULL DEFAULT '50.0',
    min_tranche_percentage TEXT NOT NULL DEFAULT '10.0',
    dca_interval_hours INTEGER NOT NULL DEFAULT 24,
    target_zones TEXT,
    stop_loss_percentage TEXT,
    take_profit_percentage TEXT,
    total_invested TEXT NOT NULL DEFAULT '0.0',
    total_purchased TEXT NOT NULL DEFAULT '0.0',
    average_buy_price TEXT,
    last_execution_at TEXT,
    next_execution_at TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);
