CREATE TABLE IF NOT EXISTS sma_crossover_strategies (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL,
    name TEXT NOT NULL,
    asset_symbol TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'active',
    config_json TEXT NOT NULL,
    total_invested REAL NOT NULL DEFAULT 0.0,
    total_purchased REAL NOT NULL DEFAULT 0.0,
    average_buy_price REAL,
    current_position INTEGER NOT NULL DEFAULT 0,
    total_trades INTEGER NOT NULL DEFAULT 0,
    winning_trades INTEGER NOT NULL DEFAULT 0,
    losing_trades INTEGER NOT NULL DEFAULT 0,
    realized_pnl REAL NOT NULL DEFAULT 0.0,
    unrealized_pnl REAL,
    current_streak INTEGER NOT NULL DEFAULT 0,
    max_drawdown REAL,
    last_fast_sma REAL,
    last_slow_sma REAL,
    last_signal_type TEXT,
    last_signal_time TEXT,
    last_execution_at TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);
