CREATE TABLE IF NOT EXISTS grid_trading_strategies (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL,
    name TEXT NOT NULL,
    asset_symbol TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'active',
    config_json TEXT NOT NULL,
    total_invested REAL NOT NULL DEFAULT 0.0,
    total_purchased REAL NOT NULL DEFAULT 0.0,
    average_buy_price REAL,
    current_inventory REAL NOT NULL DEFAULT 0.0,
    grid_levels_count INTEGER NOT NULL DEFAULT 0,
    total_trades INTEGER NOT NULL DEFAULT 0,
    winning_trades INTEGER NOT NULL DEFAULT 0,
    losing_trades INTEGER NOT NULL DEFAULT 0,
    realized_pnl REAL NOT NULL DEFAULT 0.0,
    unrealized_pnl REAL,
    max_drawdown REAL,
    grid_center_price REAL,
    grid_upper_bound REAL,
    grid_lower_bound REAL,
    last_rebalance_at TEXT,
    total_grid_profit REAL NOT NULL DEFAULT 0.0,
    active_buy_orders INTEGER NOT NULL DEFAULT 0,
    active_sell_orders INTEGER NOT NULL DEFAULT 0,
    last_execution_at TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);
